# Generated by Django 5.1.4 on 2026-03-20 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_generalnewsmodel_options_and_more'),
        ('tournaments', '0021_disliketotournamentnews_liketotournamentnews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DislikeToGeneralNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_by_general_news', to='tournaments.tournamentnewsmodel', verbose_name='генеральная новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_to_general_news', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'дизлайк на генеральную новость',
                'verbose_name_plural': 'дизлайки на генеральную новость',
            },
        ),
        migrations.CreateModel(
            name='LikeToGeneralNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_to_general_news', to='tournaments.tournamentnewsmodel', verbose_name='генеральная новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_to_general_news', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'лайк на генеральную новость',
                'verbose_name_plural': 'лайки на генеральную новость',
            },
        ),
    ]
