# Generated by Django 5.1.4 on 2026-03-20 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_alter_tournamentmodel_judges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DislikeToTournamentNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_to_tournament_news', to='tournaments.tournamentnewsmodel', verbose_name='турнирная новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_to_tournament_news', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'дизлайк на турнирную новость',
                'verbose_name_plural': 'дизлайки на турнирную новость',
            },
        ),
        migrations.CreateModel(
            name='LikeToTournamentNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_to_tournament_news', to='tournaments.tournamentnewsmodel', verbose_name='турнирная новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_to_tournament_news', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'лайк на турнирную новость',
                'verbose_name_plural': 'лайки на турнирную новость',
            },
        ),
    ]
