from django.urls import path
from django.views.generic import TemplateView

from tournaments import views

app_name = "tournaments"

urlpatterns = [
    path(
        "create",
        views.TournamentCreateView.as_view(),
        name="create_tournament",
    ),
    path(
        "",
        views.AllTournamentsView.as_view(),
        name="all_tournaments",
    ),
    path(
        "<int:tournament_id>/send_request_team_tournament",
        views.SendRequestToTournamentView.as_view(),
        name="send_request_team_tournament",
    ),
    path(
        "user_all_request_team_tournament",
        views.UserAllRequestTeamTournament.as_view(),
        name="user_all_request_team_tournament",
    ),
    path(
        "<int:tournament_id>/manage/requests/<str:status_filter>",
        views.ManageTornamentRequests.as_view(),
        name="manage_tournament_requests",
    ),
    path(
        "<int:tournament_id>/manage/battles",
        views.ManageBattleView.as_view(),
        name="manage_tournament_battles",
    ),
    path(
        "<int:tournament_id>/manage/battles/create",
        views.CreateBattleView.as_view(),
        name="create_battle",
    ),
    path(
        "<int:tournament_id>/manage/battles/<int:battle_id>/edit",
        views.EditBattleView.as_view(),
        name="edit_battle",
    ),
    path(
        "<int:tournament_id>/manage/battles/<int:battle_id>/remove",
        views.DeleteBattleView.as_view(),
        name="delete_battle",
    ),
    path(
        "<int:tournament_id>/manage/judges",
        views.ManageJudgesView.as_view(),
        name="manage_tournament_judges",
    ),
    path(
        "<int:tournament_id>/manage/teams",
        views.ManageTeamsTournamentView.as_view(),
        name="manage_tournament_teams",
    ),
    path(
        "<int:tournament_id>/manage/teams/<int:team_id>/delete",
        views.DeleteTeamTournamentView.as_view(),
        name="delete_tournament_team",
    ),
    path(
        "<int:tournament_id>/manage/judges/<int:user_id>/remove",
        views.JudgeDeleteView.as_view(),
        name="remove_judge",
    ),
    path(
        "tournament_reg_is_closed",
        TemplateView.as_view(
            template_name="includes/error.html",
            extra_context={
                "error_message": "Tournament Registration Teams is Closed",
            },
        ),
        name="tournament_reg_is_closed",
    ),
    path(
        "<int:tournament_id>/manage/requests/<int:tournament_request_id>/accept",
        views.AcceptTournamentRequest.as_view(),
        name="tournament_request_accept",
    ),
    path(
        "<int:tournament_id>/manage/requests/<int:tournament_request_id>/reject",
        views.RejectTournamentRequest.as_view(),
        name="tournament_request_reject",
    ),
    path(
        "<int:tournament_id>/news",
        views.AllTournamentNewsView.as_view(),
        name="tournament_news",
    ),
    path(
        "<int:tournament_id>/news/create",
        views.CreateTournamentNewsView.as_view(),
        name="tournament_create_news",
    ),
    path(
        "<int:tournament_id>/news/<int:tournament_news_id>/edit",
        views.EditTournamentNewsView.as_view(),
        name="tournament_edit_news",
    ),
]
